language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt
script:
  - flake8 setup.py
  - flake8 django_visitor_information/

notifications:
  email:
    - tomaz+travisci@tomaz.me
